-- AlterTable
ALTER TABLE "Agent" ADD COLUMN     "monthlyEmailLimit" INTEGER NOT NULL DEFAULT 200,
ADD COLUMN     "monthlyEmailsSent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "monthlyResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
